# Generated by Django 2.2 on 2019-04-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
