# Generated by Django 2.2 on 2019-04-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
    ]
